// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoResponse struct {
	ID string `json:"id"`
}

type NewTodo struct {
	Text string `json:"text"`
}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	IsDone bool   `json:"is_done"`
}
